# Created with WinGet Updater using komac v2.6.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.defaultLocale.1.6.0.schema.json

PackageIdentifier: glzr-io.zebar
PackageVersion: 2.4.0
PackageLocale: en-US
Publisher: Glzr Software Pte. Ltd.
PublisherUrl: https://github.com/glzr-io
PublisherSupportUrl: https://github.com/glzr-io/zebar/issues
Author: glzr.io
PackageName: Zebar
PackageUrl: https://github.com/glzr-io/zebar
License: GPL-3.0
LicenseUrl: https://github.com/glzr-io/zebar/blob/HEAD/LICENSE.md
ShortDescription: Zebar creates cross-platform taskbars, desktop widgets, and popups.
Description: Zebar is a tool for creating customizable and cross-platform taskbars, desktop widgets, and popups.
Moniker: zebar
Tags:
- bar
- desktop
- dock
- linux
- macos
- ricing
- statusbar
- taskbar
- unixporn
- widget
- windows
ReleaseNotes: |-
  🎉 New features
  - Add settings UI for editing widget configs (#132).
  - Rename defaultPlacements -> presets in widget configs (non-breaking: configs will be automatically migrated).
  🐛 Bug fixes
  - Fix issue where defaultGateway.signalStrength and defaultGateway.ssid on network provider were null on non-English systems (#125).
  🚨 Breaking change
  Not sure if anyone has used these API's yet, but the following have been changed:
  - Remove open-widget-default CLI command. Replaced with new start-widget and start-preset CLI commands for dynamically starting widgets.
  - Remove startWidgetDefault JS API. Replaced with startWidget and startPreset JS functions.

  Big thanks to @SebasF1349 and @lars-berger for contributing to this release 💛
ReleaseNotesUrl: https://github.com/glzr-io/zebar/releases/tag/v2.4.0
ManifestType: defaultLocale
ManifestVersion: 1.6.0
