# Created with WinGet Updater using komac v2.6.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.defaultLocale.1.6.0.schema.json

PackageIdentifier: glzr-io.zebar
PackageVersion: 2.3.0
PackageLocale: en-US
Publisher: Glzr Software Pte. Ltd.
PublisherUrl: https://github.com/glzr-io
PublisherSupportUrl: https://github.com/glzr-io/zebar/issues
Author: glzr.io
PackageName: Zebar
PackageUrl: https://github.com/glzr-io/zebar
License: GPL-3.0
LicenseUrl: https://github.com/glzr-io/zebar/blob/HEAD/LICENSE.md
ShortDescription: Zebar creates cross-platform taskbars, desktop widgets, and popups.
Description: Zebar is a tool for creating customizable and cross-platform taskbars, desktop widgets, and popups.
Moniker: zebar
Tags:
- bar
- desktop
- dock
- linux
- macos
- ricing
- statusbar
- taskbar
- unixporn
- widget
- windows
ReleaseNotes: |-
  🎉 New features
  - Adjust widget position for monitor DPI (#119).
      - Fixes issues where the widget window was getting positioned/sized incorrectly.
  - Account for window width and height in anchor position (#122).
      - e.g. "anchor": "bottom_left" would previously place the top left corner of the window at the bottom left of the monitor and would then have to be manually offset. Now, it places the bottom-left corner of the window in the bottom-left of the monitor.
  🐛 Bug fixes
  - Fix incorrect casing in query monitors CLI command response.
  - Hide scrollbar on overflow in example templates (#120).
  🛠️️ Internal changes
  - Bump glazewm package to latest.

  Big thanks to @JonasWischeropp, @adriankarlen, and @lars-berger for contributing to this release 💛
ReleaseNotesUrl: https://github.com/glzr-io/zebar/releases/tag/v2.3.0
ManifestType: defaultLocale
ManifestVersion: 1.6.0
