# Created with WinGet Updater using komac v2.6.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.6.0.schema.json

PackageIdentifier: glzr-io.zebar
PackageVersion: 2.3.0
InstallerLocale: en-US
InstallerType: wix
Scope: machine
UpgradeBehavior: install
ProductCode: '{973C8E02-0C9D-4A14-96EC-2AACA619A597}'
ReleaseDate: 2024-10-04
AppsAndFeaturesEntries:
- DisplayName: Zebar
  Publisher: Glzr Software Pte. Ltd.
  ProductCode: '{973C8E02-0C9D-4A14-96EC-2AACA619A597}'
  UpgradeCode: '{570D3DD8-FDBD-5B5C-A519-2FF34BA60B33}'
InstallationMetadata:
  DefaultInstallLocation: '%ProgramFiles%/glzr.io/Zebar'
Installers:
- Architecture: x64
  InstallerUrl: https://github.com/glzr-io/zebar/releases/download/v2.3.0/zebar-v2.3.0-opt1-x64.msi
  InstallerSha256: DFDE14BA8F0F0CA214D633AAA0C4BB721672F8D30BA1C9CDA27E0D5FBBD4A93C
ManifestType: installer
ManifestVersion: 1.6.0
